# This action is for send runtime commands for panda robot position control

# goal
trajectory_msgs/JointTrajectoryPoint goal_pos
---
# result
trajectory_msgs/JointTrajectory traj_plan
bool success
string error
---
# feedback
trajectory_msgs/JointTrajectoryPoint current_pos